/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SetupForms;

import AccessSystem.Controller;
import AccessSystem.Enumerations.PersonType;
import AccessSystem.Factories.PersonFactory;
import AccessSystem.People.BaseInformation.InformationStructPeople;
import AccessSystem.People.BaseInformation.Person;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author li
 */
public class RegisterSetup extends javax.swing.JFrame {

    private DefaultListModel roleList;
    private Controller Controller;

    /**
     * Creates new form RegisterSetup
     */
    public RegisterSetup() {

    }

    /**
     * This form is used to add a person to the current system register and give them 
     * @param controller The controller that has each person assigned to.
     */
    public RegisterSetup(Controller controller) {

        this.Controller = controller;

        roleList = new DefaultListModel();

        initComponents();
        for (PersonType p : PersonType.values()) {
            this.rolesCombo.addItem(p.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleListview = new javax.swing.JList<>();
        rolesCombo = new javax.swing.JComboBox<>();
        addRolesBtn = new javax.swing.JButton();
        saveRoleBtn = new javax.swing.JButton();
        deleteRoleBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Person");

        jLabel2.setText("Name:");

        jLabel3.setText("User Roles");

        roleListview.setModel(roleList);
        roleListview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleListviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roleListview);

        rolesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesComboActionPerformed(evt);
            }
        });

        addRolesBtn.setText("Add");
        addRolesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRolesBtnActionPerformed(evt);
            }
        });

        saveRoleBtn.setText("Save");
        saveRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRoleBtnActionPerformed(evt);
            }
        });

        deleteRoleBtn.setText("Delete");
        deleteRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoleBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("Start");
        jMenu1.setName("StartMenuBtn"); // NOI18N

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Made by Liam Read");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameTxt))
                                    .addComponent(saveRoleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRolesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rolesCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteRoleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rolesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(addRolesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteRoleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveRoleBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void addRolesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRolesBtnActionPerformed

        int Index1 = rolesCombo.getSelectedIndex();

        ArrayList Types = new ArrayList();

        for (PersonType p : PersonType.values()) {
            Types.add(p.toString());
        }

        if (!roleList.contains(Types.get(Index1))) {
            roleList.addElement(Types.get(Index1));
        }


    }//GEN-LAST:event_addRolesBtnActionPerformed

    private void deleteRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoleBtnActionPerformed
        int Index1 = roleListview.getSelectedIndex();

        roleList.remove(Index1);

    }//GEN-LAST:event_deleteRoleBtnActionPerformed

    private void roleListviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleListviewMouseClicked

    }//GEN-LAST:event_roleListviewMouseClicked

    private void saveRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRoleBtnActionPerformed
        if (this.roleList.size() > 0) {

            try {
                InformationStructPeople tempInfoStruct = new InformationStructPeople();

                tempInfoStruct.setName(nameTxt.getText());

                List<PersonType> tempPersonList = new ArrayList<>();

                for (Object p : roleList.toArray()) {

                    switch (p.toString()) {
                        case "STUDENT":
                            tempPersonList.add(PersonType.STUDENT);
                            break;
                        case "CLEANER":
                            tempPersonList.add(PersonType.CLEANER);
                            break;
                        case "STAFFMEMBER":
                            tempPersonList.add(PersonType.STAFFMEMBER);
                            break;
                        case "VISITOR":
                            tempPersonList.add(PersonType.VISITOR);
                            break;
                        case "MANAGER":
                            tempPersonList.add(PersonType.MANAGER);
                            break;
                        case "SECURITY":
                            tempPersonList.add(PersonType.SECURITY);
                            break;
                        case "EMERGENCYRESPONDER":
                            tempPersonList.add(PersonType.EMERGENCYRESPONDER);
                            break;
                    }
                }
                tempInfoStruct.setRoles(tempPersonList);

                Controller.getSystemRegister().addPerson(tempInfoStruct);
                this.dispose();
            } catch (IndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "You must enter at least one role", "No user Types Added", JOptionPane.WARNING_MESSAGE);
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "You must enter at least one role", "No user Types Added", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_saveRoleBtnActionPerformed

    private void rolesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolesComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRolesBtn;
    private javax.swing.JButton deleteRoleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JList<String> roleListview;
    private javax.swing.JComboBox<String> rolesCombo;
    private javax.swing.JButton saveRoleBtn;
    // End of variables declaration//GEN-END:variables
}
