/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemOverview;

import AccessSystem.Logging.AccessLogEntry;
import AccessSystem.Logging.EmergencyLogEntry;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Liam Read
 */
public class LoggingForm extends javax.swing.JFrame {

    private DefaultTableModel AccessLogsModel;
    private DefaultTableModel EmergencyLogs;

    /**
     * Creates new form LoggingForm
     *
     * @param accessLogEntries all Access log entries.
     * @param emergencyLogEntries all emergency log entries
     */
    public LoggingForm(List<AccessLogEntry> accessLogEntries, List<EmergencyLogEntry> emergencyLogEntries) {

        this.AccessLogsModel = new DefaultTableModel();
        this.EmergencyLogs = new DefaultTableModel();
        initComponents();

        String[] headers = {"AccessTime", "User Name", "ID number", "Building Code", "Floor Name", "Room Number", "Permission Granted"};

        for (String s : headers) {
            this.AccessLogsModel.addColumn(s);
        }

        for (AccessLogEntry e : accessLogEntries) {
            String[] tempEntry = {e.getAccessTime(), e.getUserName(), e.getIDnumber().toString(), e.getBuildingCode(), e.getFloorName(), e.getRoomNumber(), e.getPermissionGranted()};

            this.AccessLogsModel.addRow(tempEntry);
        }

        String[] emergencyHeaders = {"Date", "Time", "Type", "Reason"};

        for (String s : emergencyHeaders) {
            this.EmergencyLogs.addColumn(s);
        }

        for (EmergencyLogEntry e : emergencyLogEntries) {
            String[] tempEntry = {e.getDate(), e.getTime(), e.getArchitectureType(), e.getReason()};
            this.EmergencyLogs.addRow(tempEntry);
        }
    }

    private LoggingForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userAccessLogs = new javax.swing.JTable();
        userAccessTxt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        emergencyTxt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mainMenuBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userAccessLogs.setModel(AccessLogsModel);
        userAccessLogs.setToolTipText("");
        jScrollPane1.setViewportView(userAccessLogs);

        userAccessTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userAccessTxt.setText("User Access Logs");

        jTable2.setModel(EmergencyLogs);
        jScrollPane2.setViewportView(jTable2);

        emergencyTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emergencyTxt.setText("Emergency Logs");

        jMenu1.setText("Start");
        jMenu1.setName("StartMenuBtn"); // NOI18N

        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(mainMenuBtn);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Made by Liam Read");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(emergencyTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(userAccessTxt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAccessTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(emergencyTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emergencyTxt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem mainMenuBtn;
    private javax.swing.JTable userAccessLogs;
    private javax.swing.JLabel userAccessTxt;
    // End of variables declaration//GEN-END:variables
}
