/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemOverview;

import AccessSystem.Architecture.Room;
import AccessSystem.Architecture.University;
import AccessSystem.Controller;
import AccessSystem.People.BaseInformation.Person;
import AccessSystem.PersonRegister;
import SetupForms.Credentails;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Liam Read
 */
public class SystemOverview extends javax.swing.JFrame {

    private final Controller controller;
    private final University university;
    private final PersonRegister register;
    private DefaultListModel campusModel;
    private DefaultListModel buildingModel;
    private DefaultListModel floorModel;
    private DefaultListModel roomModel;
    private DefaultListModel personModel;
    private DefaultListModel funcModel;

    /**
     * Creates new form SystemOverview
     *
     * @param selectedController The selected controller to be used.
     */
    public SystemOverview(Controller selectedController) {
        controller = selectedController;
        personModel = new DefaultListModel();
        buildingModel = new DefaultListModel();
        campusModel = new DefaultListModel();
        floorModel = new DefaultListModel();
        roomModel = new DefaultListModel();
        funcModel = new DefaultListModel();
        initComponents();

        this.university = selectedController.getUniversities();

        this.register = selectedController.getSystemRegister();

        this.universityTxt.setText("University: " + this.university.getUniversityName());
        register.getRegister().stream().forEach((p) -> {
            this.personModel.addElement(p.getName());
        });
        this.controller.setActiveSys(true);
    }

    private SystemOverview() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccessDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        Accesslbl = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        universityTxt = new javax.swing.JLabel();
        peopleTxt = new javax.swing.JLabel();
        campusTxt = new javax.swing.JLabel();
        buildingTxt = new javax.swing.JLabel();
        floorTxt = new javax.swing.JLabel();
        roomNumblbl = new javax.swing.JLabel();
        buildingCodeTxt = new javax.swing.JLabel();
        functionalityTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        personList = new javax.swing.JList<>();
        getUserAccess = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomListView = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        buildingListView = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        campusListview = new javax.swing.JList<>();
        selectedRoomLbl = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        floorListView = new javax.swing.JList<>();
        floorTxt1 = new javax.swing.JLabel();
        OperatingModelbl = new javax.swing.JLabel();
        getCreds = new javax.swing.JButton();
        editUserPriv = new javax.swing.JButton();
        EmergencyBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        currentLogFileBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        AccessDialog.setMinimumSize(new java.awt.Dimension(200, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Room access:");
        jLabel1.setToolTipText("");

        Accesslbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Accesslbl.setText("lbl");

        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccessDialogLayout = new javax.swing.GroupLayout(AccessDialog.getContentPane());
        AccessDialog.getContentPane().setLayout(AccessDialogLayout);
        AccessDialogLayout.setHorizontalGroup(
            AccessDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccessDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccessDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccessDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AccessDialogLayout.createSequentialGroup()
                        .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccessDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Accesslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        AccessDialogLayout.setVerticalGroup(
            AccessDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccessDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Accesslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Overview");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        universityTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        universityTxt.setText("University: ");

        peopleTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        peopleTxt.setText("People");

        campusTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campusTxt.setText("Campuses");

        buildingTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buildingTxt.setText("Buildings");

        floorTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        floorTxt.setText("Floor");

        roomNumblbl.setText("Room Number:");

        buildingCodeTxt.setText("Building Code:");

        functionalityTxt.setText("Room Functionality");

        jList1.setModel(funcModel);
        jScrollPane1.setViewportView(jList1);

        personList.setModel(personModel);
        jScrollPane2.setViewportView(personList);

        getUserAccess.setText("Simulate User");
        getUserAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUserAccessActionPerformed(evt);
            }
        });

        roomListView.setModel(roomModel);
        roomListView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomListViewMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(roomListView);

        buildingListView.setModel(buildingModel);
        buildingListView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        buildingListView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildingListViewMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(buildingListView);

        campusListview.setModel(campusModel);
        campusListview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campusListviewMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(campusListview);

        selectedRoomLbl.setText("Selected Room: ");

        floorListView.setModel(floorModel);
        floorListView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorListViewMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(floorListView);

        floorTxt1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        floorTxt1.setText("Room");

        OperatingModelbl.setText(" Operating Mode: ");

        getCreds.setText("Get User Credentials");
        getCreds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCredsActionPerformed(evt);
            }
        });

        editUserPriv.setText("Edit User Privileges");
        editUserPriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserPrivActionPerformed(evt);
            }
        });

        EmergencyBtn.setText("Emergency");
        EmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Normal Mode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        currentLogFileBtn.setText("View Current Log File");
        currentLogFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentLogFileBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("Start");
        jMenu1.setName("StartMenuBtn"); // NOI18N

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Made by Liam Read");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(universityTxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buildingCodeTxt)
                                    .addComponent(roomNumblbl)
                                    .addComponent(selectedRoomLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buildingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(floorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(floorTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmergencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(currentLogFileBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(OperatingModelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(functionalityTxt)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(peopleTxt)
                                    .addGap(57, 57, 57)))
                            .addComponent(getUserAccess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getCreds, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(editUserPriv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(universityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peopleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getUserAccess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCreds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editUserPriv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(functionalityTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(OperatingModelbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(selectedRoomLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roomNumblbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildingCodeTxt)
                                .addGap(20, 20, 20))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmergencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentLogFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        peopleTxt.getAccessibleContext().setAccessibleName("peopleListTxt");
        campusTxt.getAccessibleContext().setAccessibleName("CampusTxt");
        buildingTxt.getAccessibleContext().setAccessibleName("BuildingTxt");
        floorTxt.getAccessibleContext().setAccessibleName("FloorTxt");
        roomNumblbl.getAccessibleContext().setAccessibleName("roomNumberTxt");
        buildingCodeTxt.getAccessibleContext().setAccessibleName("buildingCodeTxt");
        functionalityTxt.getAccessibleContext().setAccessibleName("functioanlityListTxt");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.controller.setActiveSys(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        university.getCampusList().stream().forEach((c) -> {
            this.campusModel.addElement(c.getCampusName());
        });
    }//GEN-LAST:event_formWindowOpened

    private void campusListviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campusListviewMouseClicked
        try {
            int index = this.campusListview.getSelectedIndex();

            this.buildingModel.clear();
            this.floorModel.clear();
            this.roomModel.clear();

            university.getCampusList().get(index).getBuilding().stream().forEach((b) -> {
                this.buildingModel.addElement(b.getBuildingName());
            });

            this.OperatingModelbl.setText("Operating Mode:" + this.university.getCampusList().get(index).getCampusMode());
            clearRoomSettings();
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "There are no campuses to select", "No user Types Added", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_campusListviewMouseClicked

    private void buildingListViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingListViewMouseClicked

        try {
            int index = this.campusListview.getSelectedIndex();
            int index1 = this.buildingListView.getSelectedIndex();

            this.floorModel.clear();
            this.roomModel.clear();

            university.getCampusList().get(index).getBuilding().get(index1).getFloorsInBuilding().stream().forEach((f) -> {
                this.floorModel.addElement(f.getFloorIdentifer());
            });
            this.OperatingModelbl.setText(" Operating Mode: " + university.getCampusList().get(index).getBuilding().get(index1).getBuildingMode());

            clearRoomSettings();
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "There are no buildings to select", "No user Types Added", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buildingListViewMouseClicked

    private void floorListViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorListViewMouseClicked

        try {
            int index = this.campusListview.getSelectedIndex();
            int index1 = this.buildingListView.getSelectedIndex();
            int index2 = this.floorListView.getSelectedIndex();

            this.roomModel.clear();

            university.getCampusList().get(index).getBuilding().get(index1).getFloorsInBuilding().get(index2).getRoomsOnFloor().stream().forEach((room) -> {
                this.roomModel.addElement(room.getRoomName());
            });

            this.OperatingModelbl.setText(" Operating Mode: " + university.getCampusList().get(index).getBuilding().get(index1).getFloorsInBuilding().get(index2).getFloorMode());

            clearRoomSettings();
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "There are no floors to select", "No user Types Added", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_floorListViewMouseClicked

    private void roomListViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomListViewMouseClicked

        try {
            int index = this.campusListview.getSelectedIndex();
            int index1 = this.buildingListView.getSelectedIndex();
            int index2 = this.floorListView.getSelectedIndex();
            int index3 = this.roomListView.getSelectedIndex();

            clearRoomSettings();

            Room selectedRoom = university.getCampusList().get(index).getBuilding().get(index1).getFloorsInBuilding().get(index2).getRoomsOnFloor().get(index3);

            this.selectedRoomLbl.setText("Selected Room: " + selectedRoom.getRoomName());
            this.roomNumblbl.setText("Room Number: " + selectedRoom.getRoomNumber().toString());
            this.buildingCodeTxt.setText("Building Code: " + selectedRoom.getBuildingCode());
            this.OperatingModelbl.setText(" Operating Mode: " + selectedRoom.getRoomMode());

            selectedRoom.getRoomFunctionality().stream().forEach((p) -> {
                this.funcModel.addElement(p);
            });
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "There are no roomt to select", "No user Types Added", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_roomListViewMouseClicked

    private void getUserAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUserAccessActionPerformed
        int personIndex = personList.getSelectedIndex();
        Person selectedPerson = this.register.getRegister().get(personIndex);
        int index = this.campusListview.getSelectedIndex();
        int index1 = this.buildingListView.getSelectedIndex();
        int index2 = this.floorListView.getSelectedIndex();
        int index3 = this.roomListView.getSelectedIndex();
        Room selectedRoom = university.getCampusList().get(index).getBuilding().get(index1).getFloorsInBuilding().get(index2).getRoomsOnFloor().get(index3);

        boolean answer = false;
        try {
            answer = selectedRoom.getAccess(selectedPerson);
        } catch (IOException ex) {
            Logger.getLogger(SystemOverview.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "User Acess: " + answer, "User Access", JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_getUserAccessActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        this.AccessDialog.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void getCredsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCredsActionPerformed

        int index1 = this.personList.getSelectedIndex();

        Person selectedPerson = this.register.getRegister().get(index1);
        new Credentails(selectedPerson).setVisible(true);
    }//GEN-LAST:event_getCredsActionPerformed

    private void editUserPrivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserPrivActionPerformed
        int personIndex = personList.getSelectedIndex();
        Person selectedPerson = this.register.getRegister().get(personIndex);
        new AccessChangeForm(selectedPerson).setVisible(true);

    }//GEN-LAST:event_editUserPrivActionPerformed

    private void EmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyBtnActionPerformed

        try {
            new OperatingForm(this.university.getUniversityName(), this.controller, true).setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "You have not selected a Campus", "Operating Range", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_EmergencyBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new OperatingForm(this.university.getUniversityName(), this.controller, false).setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "You have not selected a Campus", "Operating Range", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void currentLogFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentLogFileBtnActionPerformed
        int index = this.campusListview.getSelectedIndex();
        int index1 = this.buildingListView.getSelectedIndex();
        int index2 = this.floorListView.getSelectedIndex();
        int index3 = this.roomListView.getSelectedIndex();

        try {
            new LoggingForm(this.controller.getUniversities().getCampusList().get(index).getAccessLogger().getLoggerEntries(), this.controller.getUniversities().getCampusList().get(index).getEmergencyLogger().getLoggerEntries()).setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            System.out.println("No Campus, Buildin or Floor was selected");
        }


    }//GEN-LAST:event_currentLogFileBtnActionPerformed

    private void clearRoomSettings() {

        this.funcModel.clear();

        this.selectedRoomLbl.setText("Selected Room: ");
        this.roomNumblbl.setText("Room Number: ");
        this.buildingCodeTxt.setText("Building Code: ");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemOverview.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SystemOverview().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AccessDialog;
    private javax.swing.JLabel Accesslbl;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton EmergencyBtn;
    private javax.swing.JLabel OperatingModelbl;
    private javax.swing.JLabel buildingCodeTxt;
    private javax.swing.JList<String> buildingListView;
    private javax.swing.JLabel buildingTxt;
    private javax.swing.JList<String> campusListview;
    private javax.swing.JLabel campusTxt;
    private javax.swing.JButton currentLogFileBtn;
    private javax.swing.JButton editUserPriv;
    private javax.swing.JList<String> floorListView;
    private javax.swing.JLabel floorTxt;
    private javax.swing.JLabel floorTxt1;
    private javax.swing.JLabel functionalityTxt;
    private javax.swing.JButton getCreds;
    private javax.swing.JButton getUserAccess;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel peopleTxt;
    private javax.swing.JList<String> personList;
    private javax.swing.JList<String> roomListView;
    private javax.swing.JLabel roomNumblbl;
    private javax.swing.JLabel selectedRoomLbl;
    private javax.swing.JLabel universityTxt;
    // End of variables declaration//GEN-END:variables

    private Object AccessDialog(boolean answer) {
        this.AccessDialog.setVisible(true);

        if (answer == true) {
            this.Accesslbl.setText("true");
        } else {
            this.Accesslbl.setText("False");
        }

        return this;
    }
}
